# Latihan Numpy
sumber: https://www.youtube.com/watch?v=QUT1VHiLmmI&t=674s

## Load Numpy

In [1]:
import numpy as np

## The Basics

In [2]:
a = np.array([1, 2, 3], dtype='int32')
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0, 8.0, 7.0],
              [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
a.ndim
b.ndim

2

In [5]:
# Get Shape
a.shape
# b.shape

(3,)

In [6]:
# Get type
a.dtype
# b.dtype

dtype('int32')

In [7]:
# Get size (byte(s))
a.itemsize
# b.itemsize

4

In [8]:
# Get total size (total element * byte(s))
# a.size * a.itemsize
a.nbytes

12

## Accessing/Changing Specific Elements, Rows, Columns, etc.

In [9]:
a = np.array([[1, 2, 3, 4, 5, 6, 7],
              [8, 9, 10, 11, 12, 13, 14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [10]:
a.shape

(2, 7)

In [11]:
a.ndim

2

In [12]:
# Get a specific element [row, column]
# a[1, 5]
# a[1][5]
a[1, -2]

13

In [13]:
# Get a specific row
# a[0, :]
a[0]

array([1, 2, 3, 4, 5, 6, 7])

In [14]:
# Get a specific column
a[:, 2]

array([ 3, 10])

In [15]:
# Getting a little more fancy [beginIndex:endIndex:stepSize]
a[0, 1:-1:2]

array([2, 4, 6])

In [16]:
a[1, 5] = 20
print(a)

a[:, 2] = [1, 2]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### *3-d example

In [17]:
b = np.array([[[1, 2],
               [3, 4]],
              
              [[5, 6],
               [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [18]:
# Get specific element (work outside in)
b[0, 1, 1]
b[:, 0, :]

array([[1, 2],
       [5, 6]])

In [19]:
b[:, 1, :] = [[9, 9],
              [8, 8]]

In [20]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

## Initialising Different Types of Arrays

In [21]:
# All 0s matrix
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
# All 1s matrix
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [23]:
# Any other number
np.full((2, 2), 99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [24]:
a.shape

(2, 7)

In [25]:
np.full((2, 7), 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [26]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [27]:
# Random decimal numbers
# np.random.rand(4, 2, 3)
np.random.random_sample(a.shape)

array([[0.37185561, 0.44879555, 0.85832457, 0.37824244, 0.99521721,
        0.38519466, 0.44898513],
       [0.52930404, 0.51126731, 0.79305359, 0.63575054, 0.47754658,
        0.84207846, 0.81672735]])

In [28]:
# Random integer numbers
np.random.randint(-4, 8, size=(3, 3))

array([[ 4,  0,  0],
       [ 6,  1,  0],
       [ 1,  4, -4]])

In [29]:
# The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [30]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [31]:
output = np.ones((5, 5))
print(output)

z = np.zeros((3, 3))
z[1, 1] = 9
print(z)

output[1:-1, 1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [32]:
a = np.array([1, 2, 3])
b = a
b[0] = 100

print(a)

[100   2   3]


In [33]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100

print(a)

[1 2 3]


## Mathematics

In [34]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [35]:
a + 2

array([3, 4, 5, 6])

In [36]:
a - 2

array([-1,  0,  1,  2])

In [37]:
a * 2

array([2, 4, 6, 8])

In [38]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [39]:
b = np.array([1, 0, 1, 0])
a + b

array([2, 2, 4, 4])

In [40]:
a ** 2

array([ 1,  4,  9, 16])

In [41]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [42]:
# Take the cos
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

##### Linear Algebra

In [43]:
# Matrix multiplication
a = np.ones((2, 3))
print(a)

b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [44]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

##### Statistics

In [45]:
stats = np.array([[1, 2, 3],
                  [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
np.min(stats)

1

In [47]:
np.max(stats, axis=1)

array([3, 6])

## Reorganising Arrays

In [48]:
before = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8]])
print(before.shape)

after = before.reshape((2, 2, 2))
print(after)

after = before.reshape((4, 2))
print(after)

(2, 4)
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [49]:
# Vertically stacking vectors
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack((v1, v2, v2 , v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [50]:
# Horizontally stacking vectors
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
np.hstack((h1, h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Miscellaneaous
##### Load Data from File

In [51]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

##### Boolean Masking and Advanced Indexing

In [52]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [53]:
(filedata > 50) & (filedata < 100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [54]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [55]:
# You can index with a list in Numpy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

In [56]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [57]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])